### ISSUE TITLE
"((reg_$0<inl>) is not a valid binary operation" ERROR happens

### ISSUE THREAD

**Issue by lc3412** [yujokang/APEx#1]
Hi,
I try to use APEx to get the openSSL specifications, however during the step **Generating the error specification** , "*((reg_$0<inl>) is not a valid binary operation*" ERROR happens. **((reg_$0<inl>)** in the  [combined output file] are shown below. 

How to solve this problem or what is the reason of this problem. If you have any idea, please let me know. 

Thanks,
Liz 

AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(reg_$0<inl>) + 16U:=(reg_$0<inl>) + 16U:={ [0, 0] }\reg_$0<inl>:={ [1, 4611686018427387887] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(reg_$0<inl>) + 16U:=(reg_$0<inl>) + 16U:={ [1, 18446744073709551615] }\reg_$0<inl>:={ [1, 4611686018427387887] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387888, 4611686018427387895] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387888, 4611686018427387895] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(reg_$0<inl>) + 16U:=(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [1, 4611686018427387895] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(reg_$0<inl>) + 16U:=(reg_$0<inl>) + 16U:={ [0, 0] }\reg_$0<inl>:={ [1, 4611686018427387887] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(reg_$0<inl>) + 16U:=(reg_$0<inl>) + 16U:={ [1, 18446744073709551615] }\reg_$0<inl>:={ [1, 4611686018427387887] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387888, 4611686018427387895] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387888, 4611686018427387895] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(reg_$0<inl>) + 16U:=(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [1, 4611686018427387895] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387896, 4611686018427387903] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387896, 4611686018427387903] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387896, 4611686018427387903] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387896, 4611686018427387903] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387896, 4611686018427387903] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387896, 4611686018427387903] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(reg_$0<inl>) + 16U:=(reg_$0<inl>) + 16U:={ [0, 0] }\reg_$0<inl>:={ [1, 4611686018427387887] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(reg_$0<inl>) + 16U:=(reg_$0<inl>) + 16U:={ [1, 18446744073709551615] }\reg_$0<inl>:={ [1, 4611686018427387887] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387888, 4611686018427387903] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(int) ((reg_$0<inl>) + 16U):=(int) ((reg_$0<inl>) + 16U):=\(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [4611686018427387888, 4611686018427387903] }\
AutoEPEx: RAND_bytes crypto/evp/e_des3.c:375:9;I&conj_$192{int}:=conj_$192{int}:={ [1, 2147483647] }\#98@des_ede3_wrap crypto/evp/e_des3.c:383:12;I&(reg_$0<inl>) + 16U:=(reg_$0<inl>) + 16U:=\reg_$0<inl>:={ [1, 4611686018427387903] }\

**Comment by yujokang** [comment]
I'm not sure I remember seeing expressions in this format. It seems like the (int) at the beginning is interpreted as an operand, so the next thing, which is "((reg_$0", is interpreted as the operator.
You could write a script of your own to got rid of the "(int)", or you could build from an older version of LLVM and Clang.
The SVN revisions we used were:
llvm: r258694
llvm/tools/clang: r258698

**Comment by lc3412** [comment]
After deleting the line of  the "((reg_$0", I get the result of specifications. However, in the specification file, there are also some lines prepend with **Precidition:**, what is that mean?

function,constraint,prediction,count
Prediction: BN_CTX_new,m,False,2893
Prediction: BN_CTX_new,n,True,92
Prediction: SSL_get1_session,m,False,26
Prediction: SSL_get1_session,n,True,4
Prediction: SSL_set_session,-2147483648_-1(374.0),False,374.0
Prediction: SSL_set_session,0_0(338.0),True,338.0
Prediction: SSL_set_session,1_2147483647(374.0),False,374.0
Prediction: SSL_get_wbio,m,False,28
Prediction: SSL_get_wbio,n,True,4

**Comment by yujokang** [comment]
Hi Liz,
This groups paths after a function call by their return values and predicts whether they returned an error or not. They are not part of the error specification itself, although they use it.
constraint is the constraint that LLVM placed on their output. For pointers, n is NULL and m is not NULL. Prediction is whether it's an error return value, and count is the number of paths where the return value follows the constraint.

**Comment by lc3412** [comment]
Hi Kang,
Thanks for your explanation ：） 
PS： I still have a question. During the running process, I use the file that you provide for the OpenSSL functions which names "analyze_func_list_ssl.txt" , and the functions in the specification results are contained in the "analyze_func_list_ssl.txt". So Can APEx find the specifications without providing the "XX_list.txt" ?

**Comment by yujokang** [comment]
Hi Liz,
You're very welcome!
Unfortunately not. I think you can easily list all of the API functions (eg. use LLVM to list all of the non-static functions), but I don't think it's very practical to analyze all of them.

**Comment by lc3412** [comment]
Thanks :)
